version: "3.7"

x-web-volumes: &web-volumes
  - ./server:/app:cached
  - ~/.zsh_history:/root/.bash_history

x-db-config: &db-config
  DATABASE_NAME: postgres
  DATABASE_USER: postgres
  DATABASE_PASSWORD: pgpassword
  DATABASE_HOST: db
  DATABASE_PORT: 5432
  POSTGRES_PASSWORD: pgpassword
  SECRET_KEY: secret

services:
  api:
    image: blog_api
    build:
      context: ./server
    env_file:
       - ./server/.env
    environment:
      <<: *db-config
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes: *web-volumes
    stdin_open: true
    tty: true
  db:
    image: postgres:12.5-alpine
    environment: *db-config
    logging:
      driver: none
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app:cached
      - ~/.zsh_history:/root/.bash_history
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: npm start
    stdin_open: true
    tty: true

volumes:
  sqlvolume:
